'use client'

import { useState } from 'react'
import { createGitHubPR } from '@/lib/api'
import { useAppStore } from '@/lib/store'
import { supabase } from '@/lib/supabaseClient'

interface CreatePRButtonProps {
  runId: string
  generatedCode?: Record<string, string>
}

export default function CreatePRButton({ runId, generatedCode }: CreatePRButtonProps) {
  const [isOpen, setIsOpen] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [repoUrl, setRepoUrl] = useState('')
  const [branchName, setBranchName] = useState('')
  const [title, setTitle] = useState('')
  const [description, setDescription] = useState('')
  const { addNotification } = useAppStore()

  const handleCreatePR = async () => {
    if (!repoUrl.trim()) {
      addNotification('error', 'يرجى إدخال رابط المستودع')
      return
    }

    setIsLoading(true)
    try {
      const result = await createGitHubPR(
        runId,
        repoUrl,
        branchName || `ai-generated-${runId.substring(0, 8)}`,
        title || 'AI-generated code',
        description || 'This PR was automatically generated by AI',
        generatedCode
      )

      if (result.success) {
        addNotification('success', `تم إنشاء PR بنجاح: #${result.pr_number}`)
        setIsOpen(false)
        
        // Refresh page to show PR link
        window.location.reload()
      } else {
        addNotification('error', 'فشل إنشاء PR')
      }
    } catch (error: any) {
      if (error.message?.includes('GitHub token')) {
        addNotification('error', 'يرجى ربط حساب GitHub أولاً')
      } else {
        addNotification('error', `خطأ: ${error.message}`)
      }
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <>
      <button
        onClick={() => setIsOpen(true)}
        className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors text-sm"
      >
        إنشاء Pull Request
      </button>

      {isOpen && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-neutral-900 rounded-xl border border-neutral-800 p-6 max-w-md w-full">
            <h3 className="text-lg font-medium text-neutral-200 mb-4">إنشاء Pull Request</h3>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm text-neutral-400 mb-2">رابط المستودع</label>
                <input
                  type="text"
                  value={repoUrl}
                  onChange={(e) => setRepoUrl(e.target.value)}
                  placeholder="https://github.com/owner/repo"
                  className="w-full px-3 py-2 bg-black border border-neutral-700 rounded-lg text-white text-sm"
                />
              </div>

              <div>
                <label className="block text-sm text-neutral-400 mb-2">اسم الفرع (اختياري)</label>
                <input
                  type="text"
                  value={branchName}
                  onChange={(e) => setBranchName(e.target.value)}
                  placeholder="ai-generated-code"
                  className="w-full px-3 py-2 bg-black border border-neutral-700 rounded-lg text-white text-sm"
                />
              </div>

              <div>
                <label className="block text-sm text-neutral-400 mb-2">عنوان PR</label>
                <input
                  type="text"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="AI-generated code"
                  className="w-full px-3 py-2 bg-black border border-neutral-700 rounded-lg text-white text-sm"
                />
              </div>

              <div>
                <label className="block text-sm text-neutral-400 mb-2">الوصف</label>
                <textarea
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="وصف PR..."
                  rows={3}
                  className="w-full px-3 py-2 bg-black border border-neutral-700 rounded-lg text-white text-sm resize-none"
                />
              </div>
            </div>

            <div className="flex gap-3 mt-6">
              <button
                onClick={() => setIsOpen(false)}
                className="flex-1 px-4 py-2 bg-neutral-800 text-white rounded-lg hover:bg-neutral-700 transition-colors"
              >
                إلغاء
              </button>
              <button
                onClick={handleCreatePR}
                disabled={isLoading || !repoUrl.trim()}
                className="flex-1 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors disabled:opacity-50"
              >
                {isLoading ? 'جاري...' : 'إنشاء'}
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  )
}
